### PR TITLE
Add types declaration file

### LINKED ISSUE #1: TypeScript type declaration file
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

### PR DESCRIPTION
**Pull request by geopic**
Resolves #1. I had some difficulty figuring out what type the `req` and `res` arguments in `serveFcn` and `bindTarget` are so I've left them typed as `any`. Feel free to point me to what kind of argument they're supposed to be so I can update the declaration file. If there are any other issues then let me know. :+1:

### CODE REVIEW

**Comment by roslovets** [comment]
Great work!

> I had some difficulty figuring out what type the `req` and `res` arguments

It's `req`est and `res`ponse objects defined there:
https://github.com/http-party/node-http-proxy/blob/9b96cd725127a024dabebec6c7ea8c807272223d/lib/http-proxy/passes/web-incoming.js#L27

You can find types here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7c20e8a02fe30762ebdc51c3839e31a84ab2f5d6/types/http-proxy/index.d.ts#L55

Сould you add them please?

**Comment by geopic** [comment]
Cheers @roslovets, I'll add them now

**Review by roslovets — APPROVED** [review]
Thank you!

**Comment by geopic** [comment]
No worries

**Pull request merged**
